apiVersion: v1
kind: Namespace
metadata:
  name: erp
  labels:
    name: erp

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: erp
  name: erp
  labels:
    app: erp
spec:
  serviceName: erp
  replicas: 1
  selector:
    matchLabels:
      app: erp
  template:
    metadata:
      labels:
        app: erp
    spec:
      containers:
        - name: erp
          image: saichler/erp:latest
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          volumeMounts:
            - name: hdata
              mountPath: /data
      volumes:
        - name: hdata
          hostPath:
            path: /data
            type: DirectoryOrCreate
