apiVersion: v1
kind: Namespace
metadata:
  name: erp-hcm
  labels:
    name: erp-hcm

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: erp-hcm
  name: erp-hcm
  labels:
    app: erp-hcm
spec:
  serviceName: erp-hcm
  replicas: 1
  selector:
    matchLabels:
      app: erp-hcm
  template:
    metadata:
      labels:
        app: erp-hcm
    spec:
      containers:
        - name: erp-hcm
          image: saichler/erp-hcm:latest
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          volumeMounts:
            - name: hdata
              mountPath: /data
      volumes:
        - name: hdata
          hostPath:
            path: /data
            type: DirectoryOrCreate
