apiVersion: v1
kind: Namespace
metadata:
  name: erp-logs-vnet
  labels:
    name: erp-logs-vnet

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: erp-logs-vnet
  name: erp-logs-vnet
  labels:
    app: erp-logs-vnet
spec:
  selector:
    matchLabels:
      app: erp-logs-vnet
  template:
    metadata:
      labels:
        app: erp-logs-vnet
    spec:
      hostNetwork: true
      containers:
        - name: erp-logs-vnet
          image: saichler/erp-logs-vnet:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 35004
          volumeMounts:
            - name: hdata
              mountPath: /data
      volumes:
        - name: hdata
          hostPath:
            path: /data
            type: DirectoryOrCreate